sonar.projectKey=elingo-test-5654_frontend
sonar.projectName=Elingo-Frontend
sonar.organization=elingo-test-5654

sonar.sources=src
sonar.tests=tests

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**
